/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    PresetListItem,
    PresetListItemFromJSON,
    PresetListItemToJSON,
} from '../models';

export interface FindPresetsRequest {
    songName?: string;
    artist?: string;
}

/**
 * 
 */
export class PresetControllerApi extends runtime.BaseAPI {

    /**
     */
    async findPresetsRaw(requestParameters: FindPresetsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<PresetListItem>>> {
        const queryParameters: any = {};

        if (requestParameters.songName !== undefined) {
            queryParameters['songName'] = requestParameters.songName;
        }

        if (requestParameters.artist !== undefined) {
            queryParameters['artist'] = requestParameters.artist;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/presets`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PresetListItemFromJSON));
    }

    /**
     */
    async findPresets(songName?: string, artist?: string, initOverrides?: RequestInit): Promise<Array<PresetListItem>> {
        const response = await this.findPresetsRaw({ songName: songName, artist: artist }, initOverrides);
        return await response.value();
    }

}
