---
openapi: 3.0.3
info:
  title: marshall-code-backend-quarkus API
  version: 1.0.0-SNAPSHOT
paths:
  /api/presets:
    get:
      tags:
      - Preset Resource
      operationId: findByFilter
      parameters:
      - name: artist
        in: query
        schema:
          type: string
          nullable: true
      - name: filter
        in: query
        schema:
          type: string
          nullable: true
      - name: song
        in: query
        schema:
          type: string
          nullable: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PresetCompact'
  /api/presets/recent:
    get:
      tags:
      - Preset Resource
      operationId: findRecent
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PresetCompact'
components:
  schemas:
    LocalDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50
    PresetCompact:
      required:
      - id
      - name
      - patch
      - createdAt
      type: object
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        artist:
          type: string
          nullable: true
        song:
          type: string
          nullable: true
        patch:
          type: array
          items:
            format: int32
            type: integer
        createdAt:
          $ref: '#/components/schemas/LocalDateTime'
