/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PresetListItem
 */
export interface PresetListItem {
    /**
     * 
     * @type {string}
     * @memberof PresetListItem
     */
    artist: string;
    /**
     * 
     * @type {number}
     * @memberof PresetListItem
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PresetListItem
     */
    name: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof PresetListItem
     */
    preset: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof PresetListItem
     */
    songName: string;
}

export function PresetListItemFromJSON(json: any): PresetListItem {
    return PresetListItemFromJSONTyped(json, false);
}

export function PresetListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresetListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'artist': json['artist'],
        'id': json['id'],
        'name': json['name'],
        'preset': json['preset'],
        'songName': json['songName'],
    };
}

export function PresetListItemToJSON(value?: PresetListItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'artist': value.artist,
        'id': value.id,
        'name': value.name,
        'preset': value.preset,
        'songName': value.songName,
    };
}

