name: Publish to GCR
on:
  push:
    branches:
      - master
jobs:
  increase-version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.bump-version.outputs.newTag }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - id: bump-version
        name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: increase-version

    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Build'
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist

  publish:
    needs:
      - increase-version
      - build
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3

      - id: 'auth'
        name: 'Authenticate'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: '${{ secrets.DOCKER_HOST }}'
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: '${{ secrets.DOCKER_HOST }}/${{ secrets.GCP_PROJECT_ID }}/marshall-code-frontend:${{ needs.increase-version.outputs.version }}'
