name: Publish to GCP
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Authenticate'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gsutil ls ${{ secrets.STORAGE }}'
